# Generated by Django 5.2.6 on 2025-09-24 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="类别名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分类描述"),
                ),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="分类图片"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商品类别",
                "verbose_name_plural": "商品类别",
                "db_table": "product_category",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="商品描述"),
                ),
                ("main_image", models.URLField(verbose_name="主图")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="商品图集"),
                ),
                ("points_price", models.IntegerField(verbose_name="积分价格")),
                (
                    "original_points",
                    models.IntegerField(default=0, verbose_name="原价积分"),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="库存数量")),
                ("sales_count", models.IntegerField(default=0, verbose_name="销量")),
                (
                    "detail_html",
                    models.TextField(
                        blank=True, null=True, verbose_name="商品详情HTML"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "热销中"),
                            ("inactive", "下架"),
                            ("sold_out", "售罄"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="商品状态",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_recommended",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热销")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="mall.productcategory",
                        verbose_name="商品分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "product",
                "ordering": ["-sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_name", models.CharField(max_length=100, verbose_name="SKU名称")),
                ("points_price", models.IntegerField(verbose_name="积分价格")),
                ("stock", models.IntegerField(default=0, verbose_name="库存")),
                ("sales_count", models.IntegerField(default=0, verbose_name="销量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="mall.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品规格",
                "verbose_name_plural": "商品规格",
                "db_table": "product_sku",
            },
        ),
    ]
