# Generated by Django 5.2.6 on 2025-10-10 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsku",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "商品规格",
                "verbose_name_plural": "商品规格",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="detail_images",
            field=models.JSONField(blank=True, default=list, verbose_name="详情图片"),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.IntegerField(default=0, verbose_name="折扣百分比"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="是否新品"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_on_sale",
            field=models.BooleanField(default=False, verbose_name="是否打折"),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=3, verbose_name="评分"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.IntegerField(default=0, verbose_name="评价数量"),
        ),
        migrations.AddField(
            model_name="productsku",
            name="attributes",
            field=models.JSONField(default=dict, verbose_name="规格属性"),
        ),
        migrations.AddField(
            model_name="productsku",
            name="image",
            field=models.URLField(blank=True, null=True, verbose_name="SKU图片"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "热销中"),
                    ("inactive", "下架"),
                    ("sold_out", "售罄"),
                    ("restocking", "补货中"),
                ],
                default="active",
                max_length=20,
                verbose_name="商品状态",
            ),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="轮播图标题")),
                ("image", models.URLField(verbose_name="轮播图图片")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "商品"),
                            ("activity", "活动"),
                            ("url", "外部链接"),
                        ],
                        default="product",
                        max_length=20,
                        verbose_name="链接类型",
                    ),
                ),
                (
                    "activity_url",
                    models.URLField(blank=True, null=True, verbose_name="活动链接"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, null=True, verbose_name="外部链接"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="mall.product",
                        verbose_name="关联商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "轮播图",
                "db_table": "mall_banner",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1星"),
                            (2, "2星"),
                            (3, "3星"),
                            (4, "4星"),
                            (5, "5星"),
                        ],
                        verbose_name="评分",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="评价标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="评价内容")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="评价图片"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="匿名评价"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否显示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评价时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="mall.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品评价",
                "verbose_name_plural": "商品评价",
                "db_table": "product_review",
                "ordering": ["-created_at"],
            },
        ),
    ]
