# Generated by Django 5.2.6 on 2025-10-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0002_alter_productsku_options_product_detail_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="desc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="描述"
            ),
        ),
    ]
