# Generated by Django 5.2.6 on 2025-10-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0003_banner_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="icon",
            field=models.CharField(
                default="icon-default",
                help_text="小程序图标字体类名，如：icon-car, icon-electronic",
                max_length=50,
                verbose_name="图标类名",
            ),
        ),
    ]
