# Generated by Django 5.2.6 on 2025-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0004_productcategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_info",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="配送信息"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_tags",
            field=models.JSONField(blank=True, default=list, verbose_name="促销标签"),
        ),
        migrations.AddField(
            model_name="product",
            name="services",
            field=models.JSONField(blank=True, default=list, verbose_name="服务保障"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="icon",
            field=models.CharField(
                default="icon-defaults",
                help_text="小程序图标字体类名，如：icon-car, icon-electronic",
                max_length=50,
                verbose_name="图标类名",
            ),
        ),
    ]
