# Generated by Django 5.2.6 on 2025-10-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0005_product_delivery_info_product_promotion_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="delivery_info",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promotion_tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="services",
        ),
    ]
