# Generated by Django 5.2.6 on 2025-10-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0006_remove_product_delivery_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsku",
            name="attributes",
        ),
        migrations.AddField(
            model_name="productsku",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="productsku",
            name="sku_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="SKU编码"
            ),
        ),
        migrations.CreateModel(
            name="ProductSpecGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="规格组名称")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_groups",
                        to="mall.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品规格组",
                "verbose_name_plural": "商品规格组",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="规格值")),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="规格图片"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "spec_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="mall.productspecgroup",
                        verbose_name="规格组",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品规格选项",
                "verbose_name_plural": "商品规格选项",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="productsku",
            name="spec_options",
            field=models.ManyToManyField(
                related_name="skus",
                to="mall.productspecoption",
                verbose_name="规格选项",
            ),
        ),
    ]
