# Generated by Django 5.2.6 on 2025-10-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0007_remove_productsku_attributes_productsku_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsku",
            name="sku_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="SKU编码"
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="sku_name",
            field=models.CharField(max_length=200, verbose_name="SKU名称"),
        ),
    ]
