# Generated by Django 5.2.6 on 2025-10-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0008_alter_productsku_sku_code_alter_productsku_sku_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspecoption",
            name="price_increment",
            field=models.IntegerField(
                default=0,
                help_text="选择此选项时增加的价格，可以为负数",
                verbose_name="价格增量",
            ),
        ),
    ]
