# Generated by Django 5.2.6 on 2025-10-24 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0009_productspecoption_price_increment"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSpecOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="选项值")),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="选项图片"),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="颜色代码"
                    ),
                ),
                (
                    "base_price_increment",
                    models.IntegerField(default=0, verbose_name="基础价格增量"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "全局规格选项",
                "verbose_name_plural": "全局规格选项",
                "db_table": "global_spec_option",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalSpecTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="规格名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="规格描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="图标类名"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("color", "颜色"),
                            ("image", "图片"),
                            ("mixed", "混合"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="数据类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "全局规格模板",
                "verbose_name_plural": "全局规格模板",
                "db_table": "global_spec_template",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="points_price",
        ),
        migrations.RemoveField(
            model_name="productsku",
            name="points_price",
        ),
        migrations.AddField(
            model_name="product",
            name="base_points_price",
            field=models.IntegerField(default=0, verbose_name="基础积分价格"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price_calculation_method",
            field=models.CharField(
                choices=[
                    ("additive", "累加计算"),
                    ("fixed", "固定价格"),
                    ("custom", "自定义规则"),
                ],
                default="additive",
                max_length=20,
                verbose_name="价格计算方式",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="use_global_specs",
            field=models.BooleanField(default=False, verbose_name="使用全局规格"),
        ),
        migrations.AddField(
            model_name="productsku",
            name="base_points_price",
            field=models.IntegerField(default=0, verbose_name="基础积分价格"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsku",
            name="calculated_price",
            field=models.IntegerField(default=0, verbose_name="计算后价格"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsku",
            name="final_price",
            field=models.IntegerField(default=0, verbose_name="最终价格"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("main", "主规格"),
                    ("secondary", "次规格"),
                    ("display", "展示规格"),
                ],
                default="main",
                help_text="主规格影响价格，次规格辅助选择，展示规格仅用于展示",
                max_length=20,
                verbose_name="规格组类型",
            ),
        ),
        migrations.AddField(
            model_name="productspecgroup",
            name="price_weight",
            field=models.IntegerField(default=1, verbose_name="价格权重"),
        ),
        migrations.AddField(
            model_name="productspecgroup",
            name="spec_type",
            field=models.CharField(
                choices=[("global", "全局规格"), ("private", "私有规格")],
                default="private",
                max_length=20,
                verbose_name="规格类型",
            ),
        ),
        migrations.AddField(
            model_name="productspecoption",
            name="color_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="颜色代码"
            ),
        ),
        migrations.AddField(
            model_name="productspecoption",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="是否可用"),
        ),
        migrations.AddField(
            model_name="productspecoption",
            name="price_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="例如：1.1表示价格增加10%",
                max_digits=5,
                verbose_name="价格乘数",
            ),
        ),
        migrations.AddField(
            model_name="productspecoption",
            name="stock_impact",
            field=models.BooleanField(default=True, verbose_name="影响库存"),
        ),
        migrations.AlterField(
            model_name="productspecoption",
            name="price_increment",
            field=models.IntegerField(default=0, verbose_name="价格增量"),
        ),
        migrations.AddField(
            model_name="productspecoption",
            name="global_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_spec_options",
                to="mall.globalspecoption",
                verbose_name="全局规格选项",
            ),
        ),
        migrations.AddField(
            model_name="globalspecoption",
            name="spec_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_options",
                to="mall.globalspectemplate",
                verbose_name="规格模板",
            ),
        ),
        migrations.AddField(
            model_name="productspecgroup",
            name="global_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_spec_groups",
                to="mall.globalspectemplate",
                verbose_name="全局规格模板",
            ),
        ),
        migrations.CreateModel(
            name="PriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="规则描述"),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("spec_combination", "规格组合"),
                            ("quantity", "数量范围"),
                            ("user_group", "用户分组"),
                        ],
                        default="spec_combination",
                        max_length=20,
                        verbose_name="条件类型",
                    ),
                ),
                (
                    "spec_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON格式：{'规格组ID': '规格选项ID'}",
                        verbose_name="规格条件",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("fixed", "固定价格"),
                            ("increment", "价格增量"),
                            ("multiplier", "价格乘数"),
                            ("percentage", "百分比调整"),
                        ],
                        default="increment",
                        max_length=20,
                        verbose_name="调整方式",
                    ),
                ),
                (
                    "adjustment_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="调整值"
                    ),
                ),
                ("priority", models.IntegerField(default=1, verbose_name="优先级")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_rules",
                        to="mall.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格规则",
                "verbose_name_plural": "价格规则",
                "db_table": "price_rule",
                "ordering": ["priority", "-created_at"],
            },
        ),
    ]
