# Generated by Django 5.2.6 on 2025-10-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0010_globalspecoption_globalspectemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsku",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
