# Generated by Django 5.2.6 on 2025-12-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VinConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "save_query_results",
                    models.BooleanField(
                        default=True,
                        help_text="启用后，所有使用此配置的查询结果都会被保存到数据库",
                        verbose_name="保存查询结果",
                    ),
                ),
                (
                    "save_miniprogram_results",
                    models.BooleanField(
                        default=False,
                        help_text="启用后，微信小程序的VIN查询结果也会被保存到数据库",
                        verbose_name="保存小程序查询结果",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "VIN查询配置",
                "verbose_name_plural": "VIN查询配置",
                "db_table": "vin_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VinQueryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vin_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="VIN码"
                    ),
                ),
                (
                    "query_status",
                    models.CharField(
                        choices=[
                            ("pending", "待查询"),
                            ("processing", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="查询状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "query_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="查询时间"),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0, verbose_name="处理时间(秒)"),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="品牌"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="车型名称"
                    ),
                ),
                (
                    "model_year",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="车型年份"
                    ),
                ),
                (
                    "build_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="生产日期"
                    ),
                ),
                ("model_list", models.JSONField(default=list, verbose_name="车型列表")),
                (
                    "original_epc_list",
                    models.JSONField(default=list, verbose_name="原厂EPC列表"),
                ),
                (
                    "gonggao_list",
                    models.JSONField(default=list, verbose_name="公告列表"),
                ),
                (
                    "import_list",
                    models.JSONField(default=list, verbose_name="进口车型列表"),
                ),
                (
                    "original_attributes",
                    models.JSONField(default=list, verbose_name="原厂属性"),
                ),
                (
                    "raw_response_data",
                    models.JSONField(default=dict, verbose_name="原始响应数据"),
                ),
                (
                    "model_count",
                    models.IntegerField(default=0, verbose_name="车型数量"),
                ),
                (
                    "config_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vin.vinconfig",
                        verbose_name="使用的配置",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vin_query_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="查询用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "VIN查询结果",
                "verbose_name_plural": "VIN查询结果",
                "db_table": "vin_query_result",
                "ordering": ["-query_time"],
                "indexes": [
                    models.Index(fields=["vin_code"], name="idx_vin_code"),
                    models.Index(
                        fields=["user", "query_time"], name="idx_user_query_time"
                    ),
                    models.Index(fields=["query_status"], name="idx_query_status"),
                    models.Index(fields=["brand"], name="idx_brand"),
                    models.Index(fields=["model_year"], name="idx_model_year"),
                    models.Index(fields=["model_name"], name="idx_model_name"),
                ],
            },
        ),
    ]
