# Generated by Django 5.2.6 on 2025-11-06 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="配置键"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("banner", "轮播图"),
                            ("contact", "联系方式"),
                            ("process", "回收流程"),
                            ("advantage", "优势说明"),
                            ("price_tips", "价格提示"),
                        ],
                        max_length=20,
                        verbose_name="配置类型",
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="配置值")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报废车页面配置",
                "verbose_name_plural": "报废车页面配置",
                "db_table": "scrap_car_config",
            },
        ),
        migrations.CreateModel(
            name="ScrapCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=50, verbose_name="联系人姓名"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=11, verbose_name="联系电话"),
                ),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("district", models.CharField(max_length=50, verbose_name="区县")),
                ("address", models.TextField(blank=True, verbose_name="详细地址")),
                ("car_model", models.CharField(max_length=100, verbose_name="车型")),
                (
                    "car_count",
                    models.PositiveIntegerField(default=1, verbose_name="车辆数量"),
                ),
                (
                    "wheel_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="轮毂类型"
                    ),
                ),
                (
                    "wheel_count",
                    models.PositiveIntegerField(default=0, verbose_name="轮毂数量"),
                ),
                (
                    "ternary_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="三元催化器数量"
                    ),
                ),
                (
                    "battery_count",
                    models.PositiveIntegerField(default=0, verbose_name="铅蓄电池数量"),
                ),
                (
                    "battery_pack_count",
                    models.PositiveIntegerField(default=0, verbose_name="电池包数量"),
                ),
                (
                    "engine_count",
                    models.PositiveIntegerField(default=0, verbose_name="发动机数量"),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="整备质量(千克)"
                    ),
                ),
                (
                    "can_start",
                    models.BooleanField(default=True, verbose_name="能否正常启动"),
                ),
                (
                    "car_image",
                    models.ImageField(
                        upload_to="scrap_cars/%Y/%m/", verbose_name="车辆照片"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待评估"),
                            ("priced", "已报价"),
                            ("confirmed", "已同意"),
                            ("cancelled", "已取消"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "assessed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="评估价格",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最终价格",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="评估时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "报废车信息",
                "verbose_name_plural": "报废车信息",
                "db_table": "scrap_car",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecyclingProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_step",
                    models.CharField(max_length=50, verbose_name="流程步骤"),
                ),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="操作时间"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作员",
                    ),
                ),
                (
                    "scrap_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycle.scrapcar",
                        verbose_name="报废车",
                    ),
                ),
            ],
            options={
                "verbose_name": "回收流程记录",
                "verbose_name_plural": "回收流程记录",
                "db_table": "recycling_process",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessed_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="评估价格"
                    ),
                ),
                (
                    "assessment_notes",
                    models.TextField(blank=True, verbose_name="评估说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="评估时间"
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评估员",
                    ),
                ),
                (
                    "scrap_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycle.scrapcar",
                        verbose_name="报废车",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格评估记录",
                "verbose_name_plural": "价格评估记录",
                "db_table": "price_assessment",
                "ordering": ["-created_at"],
            },
        ),
    ]
