# Generated by Django 5.2.6 on 2025-11-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0004_pricerule_remove_priceassessment_car_recycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapcar",
            name="car_image_path",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="车辆照片路径"
            ),
        ),
        migrations.AlterField(
            model_name="scrapcar",
            name="car_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="scrap_cars/%Y/%m/",
                verbose_name="车辆照片",
            ),
        ),
    ]
