# Generated by Django 5.2.6 on 2025-11-07 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0005_scrapcar_car_image_path_alter_scrapcar_car_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricerule",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "价格规则",
                "verbose_name_plural": "价格规则",
            },
        ),
        migrations.AddField(
            model_name="pricerule",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="pricerule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.CreateModel(
            name="LocationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="纬度"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="经度"
                    ),
                ),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("district", models.CharField(max_length=50, verbose_name="区县")),
                ("address", models.CharField(max_length=200, verbose_name="详细地址")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "位置缓存",
                "verbose_name_plural": "位置缓存",
                "db_table": "recycle_location_cache",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="recycle_loc_latitud_0d3a49_idx",
                    )
                ],
            },
        ),
    ]
