# Generated by Django 4.2.27 on 2026-03-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0007_scrapcar_status_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="材质名称"
                    ),
                ),
                (
                    "price_per_ton",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价（元/吨）"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "车辆评估",
                "verbose_name_plural": "车辆评估",
                "db_table": "recycle_evaluation_material",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
