# Generated by Django 5.2.6 on 2025-09-24 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="轮播图图片"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="跳转链接"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "首页轮播图管理",
                "db_table": "banner",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("EngName", models.CharField(max_length=50, verbose_name="英文名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分类描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "新闻分类",
                "verbose_name_plural": "新闻分类",
                "db_table": "news_category",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="新闻标题")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/images/%Y/%m/%d/",
                        verbose_name="新闻图片",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="如果未上传图片，则显示此链接的图片",
                        verbose_name="图片链接",
                    ),
                ),
                ("content", models.TextField(verbose_name="新闻内容")),
                (
                    "source",
                    models.CharField(
                        default="", max_length=50, verbose_name="新闻来源"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="发布日期"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="访问量"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.newscategory",
                        verbose_name="新闻分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "新闻资讯",
                "verbose_name_plural": "新闻资讯",
                "db_table": "news",
                "ordering": ["-publish_date", "-created_at"],
            },
        ),
    ]
