# Generated by Django 5.2.6 on 2025-12-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newscategory",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "新闻分类",
                "verbose_name_plural": "新闻分类",
            },
        ),
        migrations.AddField(
            model_name="newscategory",
            name="order",
            field=models.IntegerField(default=0, verbose_name="首页排序"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="show_in_home",
            field=models.BooleanField(default=False, verbose_name="在首页显示"),
        ),
    ]
