# Generated by Django 5.2.6 on 2025-11-06 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarRecycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=50, verbose_name="联系人姓名"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=11, verbose_name="联系电话"),
                ),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("district", models.CharField(max_length=50, verbose_name="区域")),
                ("address", models.TextField(blank=True, verbose_name="详细地址")),
                ("car_model", models.CharField(max_length=100, verbose_name="车型")),
                (
                    "car_count",
                    models.PositiveIntegerField(default=1, verbose_name="车辆数量"),
                ),
                (
                    "wheel_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="轮毂类型"
                    ),
                ),
                (
                    "wheel_count",
                    models.PositiveIntegerField(default=0, verbose_name="轮毂数量"),
                ),
                (
                    "ternary_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="三元催化器数量"
                    ),
                ),
                (
                    "battery_count",
                    models.PositiveIntegerField(default=0, verbose_name="铅蓄电池数量"),
                ),
                (
                    "battery_pack_count",
                    models.PositiveIntegerField(default=0, verbose_name="电池包数量"),
                ),
                (
                    "engine_count",
                    models.PositiveIntegerField(default=0, verbose_name="发动机数量"),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="整备质量(千克)"
                    ),
                ),
                (
                    "can_start",
                    models.BooleanField(default=True, verbose_name="能否正常启动"),
                ),
                (
                    "car_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="car_recycle/%Y/%m/%d/",
                        verbose_name="车辆照片",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="预估价格",
                    ),
                ),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="实际价格",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待评估"),
                            ("priced", "已报价"),
                            ("confirmed", "已同意"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_recycles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "报废车回收信息",
                "verbose_name_plural": "报废车回收信息",
                "db_table": "recycle_car_recycle",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="priceassessment",
            name="assessor",
        ),
        migrations.RemoveField(
            model_name="priceassessment",
            name="scrap_car",
        ),
        migrations.RemoveField(
            model_name="recyclingprocess",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="recyclingprocess",
            name="scrap_car",
        ),
        migrations.RemoveField(
            model_name="scrapcar",
            name="user",
        ),
        migrations.DeleteModel(
            name="SystemConfig",
        ),
        migrations.DeleteModel(
            name="PriceAssessment",
        ),
        migrations.DeleteModel(
            name="RecyclingProcess",
        ),
        migrations.DeleteModel(
            name="ScrapCar",
        ),
    ]
