# Generated by Django 5.2.6 on 2025-11-06 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0002_carrecycle_remove_priceassessment_assessor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrecycle",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="carrecycle",
            name="estimated_price",
        ),
        migrations.CreateModel(
            name="PriceAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="预估价格",
                    ),
                ),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="实际价格",
                    ),
                ),
                (
                    "assessment_notes",
                    models.TextField(blank=True, verbose_name="评估备注"),
                ),
                (
                    "assessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="评估时间"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="是否最终价格"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessed_prices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评估员",
                    ),
                ),
                (
                    "car_recycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_assessment",
                        to="recycle.carrecycle",
                        verbose_name="关联的回收车辆",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格评估",
                "verbose_name_plural": "价格评估",
                "db_table": "recycle_price_assessment",
                "ordering": ["-assessed_at"],
            },
        ),
    ]
