# Generated by Django 5.2.6 on 2025-11-07 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0003_remove_carrecycle_actual_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("car_type", models.CharField(max_length=50, verbose_name="车辆类型")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基础价格"
                    ),
                ),
                (
                    "weight_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="重量系数",
                    ),
                ),
                (
                    "condition_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="车况系数",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "价格规则",
                "verbose_name_plural": "价格规则",
                "db_table": "recycle_price_rule",
            },
        ),
        migrations.RemoveField(
            model_name="priceassessment",
            name="car_recycle",
        ),
        migrations.RemoveField(
            model_name="priceassessment",
            name="assessor",
        ),
        migrations.CreateModel(
            name="ScrapCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=50, verbose_name="联系人姓名"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=11, verbose_name="联系电话"),
                ),
                ("region", models.CharField(max_length=200, verbose_name="所在地区")),
                ("address", models.TextField(blank=True, verbose_name="详细地址")),
                ("car_model", models.CharField(max_length=100, verbose_name="车型")),
                (
                    "car_count",
                    models.PositiveIntegerField(default=1, verbose_name="车辆数量"),
                ),
                (
                    "wheel_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="轮毂类型"
                    ),
                ),
                (
                    "wheel_count",
                    models.PositiveIntegerField(default=0, verbose_name="轮毂数量"),
                ),
                (
                    "ternary_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="三元催化器数量"
                    ),
                ),
                (
                    "battery_count",
                    models.PositiveIntegerField(default=0, verbose_name="铅蓄电池数量"),
                ),
                (
                    "battery_pack_count",
                    models.PositiveIntegerField(default=0, verbose_name="电池包数量"),
                ),
                (
                    "engine_count",
                    models.PositiveIntegerField(default=0, verbose_name="发动机数量"),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="整备质量(千克)"
                    ),
                ),
                (
                    "can_start",
                    models.BooleanField(default=True, verbose_name="能否正常启动"),
                ),
                (
                    "car_image",
                    models.ImageField(
                        upload_to="scrap_cars/%Y/%m/", verbose_name="车辆照片"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待评估"),
                            ("priced", "已报价"),
                            ("confirmed", "已同意"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="预估价格",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最终价格",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="提交时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "报废车回收信息",
                "verbose_name_plural": "报废车回收信息",
                "db_table": "recycle_scrap_car",
                "ordering": ["-submit_time"],
            },
        ),
        migrations.DeleteModel(
            name="CarRecycle",
        ),
        migrations.DeleteModel(
            name="PriceAssessment",
        ),
    ]
