# Generated by Django 5.2.6 on 2025-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0006_alter_pricerule_options_pricerule_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapcar",
            name="status_history",
            field=models.TextField(
                blank=True, default="[]", verbose_name="状态变更历史"
            ),
        ),
    ]
