# Generated by Django 4.2.27 on 2026-03-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0008_evaluationmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationmaterial",
            name="factor",
            field=models.DecimalField(
                decimal_places=2, default=0.56, max_digits=3, verbose_name="计算系数"
            ),
        ),
    ]
