# Generated by Django 5.2.6 on 2025-09-24 02:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="微信OpenID",
                    ),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="微信UnionID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="微信会话密钥",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="微信昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="微信头像"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "未知"), (1, "男"), (2, "女")],
                        default=0,
                        verbose_name="性别",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="积分")),
                (
                    "is_staff_member",
                    models.BooleanField(default=False, verbose_name="是否为内部员工"),
                ),
                (
                    "staff_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="员工编号",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所属部门"
                    ),
                ),
                (
                    "staff_role",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="员工角色"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否实名认证"),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="真实姓名"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="信息更新时间"),
                ),
                (
                    "last_login_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user_info",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=50, verbose_name="收货人姓名"),
                ),
                (
                    "receiver_phone",
                    models.CharField(max_length=20, verbose_name="收货人电话"),
                ),
                (
                    "country",
                    models.CharField(
                        default="中国", max_length=50, verbose_name="国家"
                    ),
                ),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("district", models.CharField(max_length=50, verbose_name="区县")),
                (
                    "detail_address",
                    models.CharField(max_length=200, verbose_name="详细地址"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="邮政编码"
                    ),
                ),
                (
                    "address_tag",
                    models.CharField(
                        choices=[
                            ("home", "家"),
                            ("company", "公司"),
                            ("school", "学校"),
                            ("other", "其他"),
                        ],
                        default="home",
                        max_length=20,
                        verbose_name="地址标签",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户地址",
                "verbose_name_plural": "用户地址",
                "db_table": "user_address",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("jd", "京东优惠券"),
                            ("mall", "商城优惠券"),
                            ("recycle", "回收优惠券"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="优惠券类型",
                    ),
                ),
                (
                    "coupon_name",
                    models.CharField(max_length=100, verbose_name="优惠券名称"),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="优惠券码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="优惠券描述"),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="优惠金额/折扣"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低订单金额",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="有效期开始")),
                ("valid_to", models.DateTimeField(verbose_name="有效期结束")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "used_order",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="使用订单"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获取时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "user_coupon",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPointsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_type",
                    models.CharField(
                        choices=[
                            ("sign", "签到"),
                            ("task", "任务奖励"),
                            ("purchase", "购物奖励"),
                            ("recycle", "回收奖励"),
                            ("consume", "消费扣除"),
                            ("year_end_reset", "年终清零"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="积分类型",
                    ),
                ),
                ("points_change", models.IntegerField(verbose_name="积分变动")),
                ("current_points", models.IntegerField(verbose_name="变动后积分")),
                (
                    "related_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="关联ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="详细说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户积分记录",
                "verbose_name_plural": "用户积分记录",
                "db_table": "user_points_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_type",
                    models.CharField(
                        choices=[
                            ("product", "商品"),
                            ("news", "资讯"),
                            ("activity", "活动"),
                        ],
                        max_length=20,
                        verbose_name="收藏类型",
                    ),
                ),
                ("item_id", models.IntegerField(verbose_name="收藏项目ID")),
                (
                    "item_name",
                    models.CharField(max_length=200, verbose_name="项目名称"),
                ),
                (
                    "item_image",
                    models.URLField(blank=True, null=True, verbose_name="项目图片"),
                ),
                (
                    "item_url",
                    models.URLField(blank=True, null=True, verbose_name="项目链接"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户收藏",
                "verbose_name_plural": "用户收藏",
                "db_table": "user_favorite",
                "ordering": ["-created_at"],
                "unique_together": {("user", "favorite_type", "item_id")},
            },
        ),
    ]
