# Generated by Django 5.2.6 on 2025-09-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login_time",
        ),
    ]
