# Generated by Django 5.2.6 on 2025-11-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_last_login_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后登录时间"
            ),
        ),
    ]
