# Generated by Django 5.2.6 on 2025-12-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_last_login_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfavorite",
            name="item_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="项目链接"
            ),
        ),
    ]
