# Generated by Django 5.2.6 on 2025-12-08 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userfavorite_item_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCREmployeeApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(max_length=50, unique=True, verbose_name="应用ID"),
                ),
                ("app_name", models.CharField(max_length=100, verbose_name="应用名称")),
                ("app_desc", models.TextField(verbose_name="应用描述")),
                (
                    "icon_class",
                    models.CharField(
                        default="iconfont icon-app",
                        max_length=100,
                        verbose_name="图标类名",
                    ),
                ),
                (
                    "app_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="应用URL"
                    ),
                ),
                ("app_config", models.JSONField(default=dict, verbose_name="应用配置")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "OCR应用系统",
                "verbose_name_plural": "OCR应用系统",
                "db_table": "ocr_employee_app",
                "ordering": ["sort_order", "app_name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="员工头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="员工编号（兼容OCR）"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ocr_user_type",
            field=models.CharField(
                choices=[
                    ("wechat", "微信用户"),
                    ("employee", "员工账号"),
                    ("admin", "管理员"),
                ],
                default="wechat",
                max_length=20,
                verbose_name="OCR用户类型",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="职位"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="staff_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="员工工号",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeLoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_ip", models.GenericIPAddressField(verbose_name="登录IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("password", "密码登录"),
                            ("wechat", "微信登录"),
                            ("token", "Token登录"),
                        ],
                        default="password",
                        max_length=20,
                        verbose_name="登录方式",
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "fail_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="失败原因"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_logins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工登录记录",
                "verbose_name_plural": "员工登录记录",
                "db_table": "employee_login_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
