# Generated by Django 5.2.6 on 2025-12-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_ocremployeeapp_user_avatar_user_employee_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="employee_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="员工编号"
            ),
        ),
    ]
