# Generated by Django 5.2.6 on 2025-12-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_employee_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OCREmployeeApp",
            new_name="EmployeeApp",
        ),
        migrations.AlterModelOptions(
            name="employeeapp",
            options={
                "ordering": ["sort_order", "app_name"],
                "verbose_name": "应用系统",
                "verbose_name_plural": "应用系统",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="ocr_user_type",
            field=models.CharField(
                choices=[
                    ("wechat", "微信用户"),
                    ("employee", "员工账号"),
                    ("admin", "管理员"),
                ],
                default="wechat",
                max_length=20,
                verbose_name="用户类型",
            ),
        ),
        migrations.AlterModelTable(
            name="employeeapp",
            table="employee_app",
        ),
    ]
