# Generated by Django 5.2.6 on 2025-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_rename_ocremployeeapp_employeeapp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeapp",
            name="app_config",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="应用配置"
            ),
        ),
    ]
