# Generated by Django 5.2.6 on 2025-12-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_employeeapp_app_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeapp",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("internal", "内部小程序页面"),
                    ("webview", "外部网页"),
                    ("hybrid", "混合应用"),
                ],
                default="internal",
                max_length=20,
                verbose_name="应用类型",
            ),
        ),
    ]
