# Generated by Django 5.2.6 on 2025-12-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_employeeapp_app_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeapp",
            name="app_type",
        ),
        migrations.AddField(
            model_name="employeeapp",
            name="access_roles",
            field=models.JSONField(blank=True, default=list, verbose_name="可访问角色"),
        ),
        migrations.AddField(
            model_name="employeeapp",
            name="internal_path",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="内部页面路径"
            ),
        ),
        migrations.AddField(
            model_name="employeeapp",
            name="miniapp_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="小程序路径"
            ),
        ),
        migrations.AddField(
            model_name="employeeapp",
            name="open_type",
            field=models.CharField(
                choices=[
                    ("internal", "内部页面"),
                    ("webview", "外部网页"),
                    ("miniapp", "跳转小程序"),
                ],
                default="internal",
                max_length=20,
                verbose_name="打开方式",
            ),
        ),
        migrations.AddField(
            model_name="employeeapp",
            name="require_auth",
            field=models.BooleanField(default=True, verbose_name="需要认证"),
        ),
        migrations.AddField(
            model_name="employeeapp",
            name="webview_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="WebView地址"
            ),
        ),
        migrations.AlterField(
            model_name="employeeapp",
            name="app_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="应用URL/路径"
            ),
        ),
    ]
