# Generated by Django 5.2.6 on 2025-12-10 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_employeeapp_app_type_employeeapp_access_roles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
        migrations.RemoveField(
            model_name="user",
            name="staff_role",
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="所属部门"),
                ),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                (
                    "staff_role",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="员工角色"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入职日期"),
                ),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("active", "在职"),
                            ("leave", "离职"),
                            ("suspended", "停职"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="在职状态",
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="工作电话"
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="工作邮箱"
                    ),
                ),
                (
                    "permission_level",
                    models.IntegerField(default=1, verbose_name="权限等级"),
                ),
                (
                    "can_access_all_apps",
                    models.BooleanField(default=False, verbose_name="可访问所有应用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工信息",
                "verbose_name_plural": "员工信息",
                "db_table": "employee_info",
                "ordering": ["department", "user__staff_id"],
            },
        ),
    ]
