# Generated by Django 5.2.6 on 2025-12-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_remove_user_avatar_remove_user_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="手机号"
            ),
        ),
    ]
