# Generated by Django 5.2.6 on 2025-12-11 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0012_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="手机号")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("register", "注册"),
                            ("bind_phone", "绑定手机号"),
                            ("reset_password", "重置密码"),
                            ("other", "其他"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="是否已使用"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "短信验证码",
                "verbose_name_plural": "短信验证码",
                "db_table": "sms_verification_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterUniqueTogether(
            name="userfavorite",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="user",
            name="ocr_user_type",
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="部门"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_bound",
            field=models.BooleanField(default=False, verbose_name="是否绑定手机号"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_wechat_bound",
            field=models.BooleanField(default=False, verbose_name="是否绑定微信"),
        ),
        migrations.AddField(
            model_name="user",
            name="merged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="合并时间"),
        ),
        migrations.AddField(
            model_name="user",
            name="merged_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="合并自用户",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="职位"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "普通用户"),
                    ("employee", "员工账号"),
                    ("admin", "管理员"),
                ],
                default="customer",
                max_length=20,
                verbose_name="账号类型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff_member",
            field=models.BooleanField(default=False, verbose_name="是否为员工"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="手机号",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone", "user_type"], name="user_info_phone_6a2267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["staff_id", "user_type"], name="user_info_staff_i_f2ec1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["openid"], name="user_info_openid_7cbced_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="user_info_created_4654c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="user_info_is_acti_3aca6e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "favorite_type", "item_id"), name="unique_user_favorite"
            ),
        ),
        migrations.AddIndex(
            model_name="smsverificationcode",
            index=models.Index(
                fields=["phone", "purpose"], name="sms_verific_phone_3997fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsverificationcode",
            index=models.Index(
                fields=["created_at"], name="sms_verific_created_b1254c_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
