# Generated by Django 5.2.6 on 2025-12-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_smsverificationcode_remove_employee_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="merged_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="merged_from",
        ),
    ]
