# Generated by Django 5.2.6 on 2025-12-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_remove_user_merged_at_remove_user_merged_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="unionid",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "该微信已被绑定"},
                max_length=100,
                null=True,
                unique=True,
                verbose_name="微信UnionID",
            ),
        ),
        migrations.DeleteModel(
            name="UserPointsRecord",
        ),
    ]
