# Generated by Django 5.2.6 on 2025-12-25 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0015_alter_user_unionid_delete_userpointsrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(max_length=50, unique=True, verbose_name="规则ID"),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="规则名称"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("sign", "签到"),
                            ("task", "任务奖励"),
                            ("purchase", "购物奖励"),
                            ("recycle", "回收奖励"),
                            ("system_bonus", "系统奖励"),
                            ("consume", "消费扣除"),
                            ("year_end_reset", "年终清零"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "green_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transport", "绿色出行"),
                            ("food", "光盘行动"),
                            ("walk", "低碳行走"),
                            ("learning", "低碳学习"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="绿色生活类型",
                    ),
                ),
                ("points_value", models.IntegerField(default=0, verbose_name="积分值")),
                (
                    "points_limit",
                    models.IntegerField(
                        default=0, verbose_name="积分上限（0表示无限制）"
                    ),
                ),
                (
                    "daily_limit",
                    models.IntegerField(default=0, verbose_name="每日上限"),
                ),
                (
                    "monthly_limit",
                    models.IntegerField(default=0, verbose_name="每月上限"),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("count", "次数达标"),
                            ("amount", "金额达标"),
                            ("days", "连续天数"),
                            ("steps", "步数达标"),
                            ("upload", "上传凭证"),
                            ("certificate", "证书认证"),
                        ],
                        default="count",
                        max_length=20,
                        verbose_name="条件类型",
                    ),
                ),
                (
                    "condition_value",
                    models.IntegerField(default=0, verbose_name="条件值"),
                ),
                (
                    "condition_unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="条件单位"
                    ),
                ),
                ("description", models.TextField(verbose_name="规则描述")),
                (
                    "instructions",
                    models.TextField(blank=True, null=True, verbose_name="操作说明"),
                ),
                (
                    "need_upload",
                    models.BooleanField(default=False, verbose_name="需要上传凭证"),
                ),
                (
                    "upload_desc",
                    models.TextField(blank=True, null=True, verbose_name="上传说明"),
                ),
                (
                    "certificate_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="证书名称"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "积分规则",
                "verbose_name_plural": "积分规则",
                "db_table": "points_rule",
                "ordering": ["sort_order", "rule_name"],
            },
        ),
        migrations.CreateModel(
            name="PointsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_type",
                    models.CharField(
                        choices=[
                            ("sign", "签到"),
                            ("task", "任务奖励"),
                            ("purchase", "购物奖励"),
                            ("recycle", "回收奖励"),
                            ("system_bonus", "系统奖励"),
                            ("consume", "消费扣除"),
                            ("year_end_reset", "年终清零"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="积分类型",
                    ),
                ),
                (
                    "green_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transport", "绿色出行"),
                            ("food", "光盘行动"),
                            ("walk", "低碳行走"),
                            ("learning", "低碳学习"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="绿色生活类型",
                    ),
                ),
                ("points_change", models.IntegerField(verbose_name="积分变动")),
                ("current_points", models.IntegerField(verbose_name="变动后积分")),
                (
                    "related_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="关联ID"
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="订单号"
                    ),
                ),
                (
                    "recycle_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="回收记录ID"
                    ),
                ),
                (
                    "upload_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="points/uploads/%Y/%m/",
                        verbose_name="上传凭证",
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="points/certificates/%Y/%m/",
                        verbose_name="证书图片",
                    ),
                ),
                ("steps_count", models.IntegerField(default=0, verbose_name="步数")),
                ("days_count", models.IntegerField(default=0, verbose_name="连续天数")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="详细说明"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_records_new",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_points_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "points_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="points.pointsrule",
                        verbose_name="积分规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分记录",
                "verbose_name_plural": "积分记录",
                "db_table": "points_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="points_reco_user_id_261fbe_idx",
                    ),
                    models.Index(
                        fields=["user", "points_type"],
                        name="points_reco_user_id_774dfa_idx",
                    ),
                    models.Index(
                        fields=["points_type", "created_at"],
                        name="points_reco_points__1959ce_idx",
                    ),
                    models.Index(
                        fields=["green_type", "is_verified"],
                        name="points_reco_green_t_a60998_idx",
                    ),
                    models.Index(
                        fields=["user", "green_type", "created_at"],
                        name="points_reco_user_id_a9d6f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="交易流水号"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "获取积分"),
                            ("redeem", "兑换商品"),
                            ("transfer", "转让积分"),
                            ("adjust", "系统调整"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                ("points_amount", models.IntegerField(verbose_name="积分数量")),
                (
                    "product_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="商品ID"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="商品名称"
                    ),
                ),
                (
                    "product_points",
                    models.IntegerField(default=0, verbose_name="商品所需积分"),
                ),
                (
                    "express_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="快递单号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "redeem_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.useraddress",
                        verbose_name="收货地址",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分交易记录",
                "verbose_name_plural": "积分交易记录",
                "db_table": "points_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_no"], name="points_tran_transac_a2e84e_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="points_tran_user_id_ef9d4a_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="points_tran_status_486701_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="points_tran_user_id_96e9e1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDailyPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "sign_points",
                    models.IntegerField(default=0, verbose_name="签到积分"),
                ),
                (
                    "task_points",
                    models.IntegerField(default=0, verbose_name="任务积分"),
                ),
                (
                    "green_points",
                    models.IntegerField(default=0, verbose_name="绿色生活积分"),
                ),
                (
                    "purchase_points",
                    models.IntegerField(default=0, verbose_name="购物积分"),
                ),
                (
                    "recycle_points",
                    models.IntegerField(default=0, verbose_name="回收积分"),
                ),
                (
                    "consume_points",
                    models.IntegerField(default=0, verbose_name="消费积分"),
                ),
                ("total_points", models.IntegerField(default=0, verbose_name="总积分")),
                (
                    "transport_days",
                    models.IntegerField(default=0, verbose_name="绿色出行天数"),
                ),
                (
                    "food_days",
                    models.IntegerField(default=0, verbose_name="光盘行动天数"),
                ),
                ("walk_steps", models.IntegerField(default=0, verbose_name="行走步数")),
                (
                    "learning_count",
                    models.IntegerField(default=0, verbose_name="学习次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户每日积分统计",
                "verbose_name_plural": "用户每日积分统计",
                "db_table": "user_daily_points",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserMonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                (
                    "total_earned",
                    models.IntegerField(default=0, verbose_name="本月获得积分"),
                ),
                (
                    "total_consumed",
                    models.IntegerField(default=0, verbose_name="本月消费积分"),
                ),
                (
                    "ending_balance",
                    models.IntegerField(default=0, verbose_name="月底余额"),
                ),
                (
                    "green_days_total",
                    models.IntegerField(default=0, verbose_name="绿色生活总天数"),
                ),
                (
                    "green_points_total",
                    models.IntegerField(default=0, verbose_name="绿色生活总积分"),
                ),
                (
                    "transport_days",
                    models.IntegerField(default=0, verbose_name="绿色出行天数"),
                ),
                (
                    "food_days",
                    models.IntegerField(default=0, verbose_name="光盘行动天数"),
                ),
                (
                    "walk_points",
                    models.IntegerField(default=0, verbose_name="低碳行走积分"),
                ),
                (
                    "learning_points",
                    models.IntegerField(default=0, verbose_name="低碳学习积分"),
                ),
                (
                    "is_transport_qualified",
                    models.BooleanField(default=False, verbose_name="绿色出行达标"),
                ),
                (
                    "is_food_qualified",
                    models.BooleanField(default=False, verbose_name="光盘行动达标"),
                ),
                (
                    "is_walk_qualified",
                    models.BooleanField(default=False, verbose_name="低碳行走达标"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_summaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户月度积分汇总",
                "verbose_name_plural": "用户月度积分汇总",
                "db_table": "user_monthly_summary",
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "year", "month")},
            },
        ),
    ]
