# Generated by Django 5.2.6 on 2025-12-31 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pointsrecord",
            index=models.Index(
                fields=["user", "points_type", "created_at"],
                name="points_reco_user_id_159fca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointsrecord",
            index=models.Index(
                fields=["created_at", "points_type"],
                name="points_reco_created_19e207_idx",
            ),
        ),
    ]
