# Generated by Django 4.2.27 on 2026-01-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0002_pointsrecord_points_reco_user_id_159fca_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointsrule",
            name="calculation_formula",
            field=models.TextField(blank=True, null=True, verbose_name="积分计算公式"),
        ),
        migrations.AddField(
            model_name="pointsrule",
            name="rule_config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="规则配置（JSON）"
            ),
        ),
        migrations.AddField(
            model_name="pointsrule",
            name="steps_config",
            field=models.JSONField(blank=True, default=list, verbose_name="步骤配置"),
        ),
        migrations.AddField(
            model_name="pointsrule",
            name="trigger_conditions",
            field=models.JSONField(blank=True, default=list, verbose_name="触发条件"),
        ),
        migrations.AddField(
            model_name="pointsrule",
            name="variables_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="变量配置"),
        ),
        migrations.CreateModel(
            name="PointsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("sign", "签到规则"),
                            ("green_life", "绿色生活"),
                            ("recycle", "回收规则"),
                            ("exchange", "兑换规则"),
                            ("system", "系统配置"),
                        ],
                        max_length=20,
                        verbose_name="配置类型",
                    ),
                ),
                ("config_key", models.CharField(max_length=100, verbose_name="配置键")),
                (
                    "config_name",
                    models.CharField(max_length=100, verbose_name="配置名称"),
                ),
                (
                    "string_value",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="字符串值"
                    ),
                ),
                (
                    "int_value",
                    models.IntegerField(blank=True, null=True, verbose_name="整数值"),
                ),
                (
                    "float_value",
                    models.FloatField(blank=True, null=True, verbose_name="浮点值"),
                ),
                (
                    "bool_value",
                    models.BooleanField(default=False, verbose_name="布尔值"),
                ),
                (
                    "json_value",
                    models.JSONField(blank=True, null=True, verbose_name="JSON值"),
                ),
                (
                    "rule_config",
                    models.JSONField(blank=True, null=True, verbose_name="规则配置"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="配置说明"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "积分系统配置",
                "verbose_name_plural": "积分系统配置",
                "db_table": "points_config",
                "ordering": ["config_type", "sort_order", "config_key"],
                "unique_together": {("config_type", "config_key")},
            },
        ),
    ]
