# Generated by Django 4.2.27 on 2026-01-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0003_pointsrule_calculation_formula_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PointsConfig",
        ),
    ]
