# Generated by Django 4.2.27 on 2026-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0004_delete_pointsconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointsrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("sign", "签到"),
                    ("sign_continuous", "连续签到奖励"),
                    ("task", "任务奖励"),
                    ("purchase", "购物奖励"),
                    ("recycle", "回收奖励"),
                    ("system_bonus", "系统奖励"),
                    ("consume", "消费扣除"),
                    ("year_end_reset", "年终清零"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="规则类型",
            ),
        ),
    ]
