# Generated by Django 4.2.27 on 2026-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0006_alter_pointsrule_rule_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单管理",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("points.pointstransaction",),
        ),
        migrations.AlterField(
            model_name="pointsrecord",
            name="points_type",
            field=models.CharField(
                choices=[
                    ("sign", "签到"),
                    ("task", "任务奖励"),
                    ("purchase", "购物奖励"),
                    ("recycle", "回收奖励"),
                    ("system_bonus", "系统奖励"),
                    ("consume", "消费扣除"),
                    ("year_end_reset", "年终清零"),
                    ("order_refund", "订单取消返还"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="积分类型",
            ),
        ),
    ]
