# Generated by Django 5.2.6 on 2025-12-08 09:10

import django.db.models.deletion
import ocr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HuaweiCloudConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("ak", models.CharField(max_length=100, verbose_name="Access Key")),
                ("sk", models.CharField(max_length=100, verbose_name="Secret Key")),
                (
                    "region",
                    models.CharField(
                        default="cn-north-4", max_length=50, verbose_name="区域"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "华为云配置",
                "verbose_name_plural": "华为云配置",
                "db_table": "ocr_huawei_cloud_config",
            },
        ),
        migrations.CreateModel(
            name="OcrInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="接口名称")),
                (
                    "interface_type",
                    models.CharField(
                        choices=[
                            ("general_text", "通用文字识别"),
                            ("id_card", "身份证识别"),
                            ("vehicle_license", "行驶证识别"),
                            ("business_license", "营业执照识别"),
                            ("auto_classification", "智能分类识别"),
                            ("vin", "VIN码查询"),
                        ],
                        max_length=50,
                        verbose_name="接口类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="接口描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "huawei_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="ocr.huaweicloudconfig",
                        verbose_name="华为云配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR接口",
                "verbose_name_plural": "OCR接口",
                "db_table": "ocr_interface",
            },
        ),
        migrations.CreateModel(
            name="CertificateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="证件名称")),
                (
                    "type_code",
                    models.CharField(
                        choices=[
                            ("id_card", "身份证"),
                            ("vehicle_license", "行驶证"),
                            ("business_license", "营业执照"),
                            ("auto", "自动识别"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="证件类型编码",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="识别关键字，逗号分隔",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_types",
                        to="ocr.ocrinterface",
                        verbose_name="关联接口",
                    ),
                ),
            ],
            options={
                "verbose_name": "证件类型",
                "verbose_name_plural": "证件类型",
                "db_table": "ocr_certificate_type",
            },
        ),
        migrations.CreateModel(
            name="RecognitionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=ocr.models.image_upload_path, verbose_name="识别图片"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ocr.models.thumbnail_upload_path,
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "recognition_status",
                    models.BooleanField(default=False, verbose_name="识别是否成功"),
                ),
                (
                    "recognition_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="识别时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "certificate_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="ocr.certificatetype",
                        verbose_name="证件类型",
                    ),
                ),
                (
                    "interface_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_records",
                        to="ocr.ocrinterface",
                        verbose_name="使用的接口",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognition_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "识别记录",
                "verbose_name_plural": "识别记录",
                "db_table": "ocr_recognition_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdCardResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="姓名"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="性别"
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="民族"
                    ),
                ),
                (
                    "birth",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="出生日期"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="住址"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="身份证号码"
                    ),
                ),
                (
                    "issue_authority",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="签发机关"
                    ),
                ),
                (
                    "valid_from",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="有效期起始"
                    ),
                ),
                (
                    "valid_to",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="有效期结束"
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("front", "人像面"),
                            ("back", "国徽面"),
                            ("double_side", "双面"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="正反面",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_card_result",
                        to="ocr.recognitionrecord",
                        verbose_name="识别记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "身份证识别结果",
                "verbose_name_plural": "身份证识别结果",
                "db_table": "ocr_id_card_result",
            },
        ),
        migrations.CreateModel(
            name="BusinessLicenseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="注册号"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="企业名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="企业类型"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="住所"
                    ),
                ),
                (
                    "legal_representative",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="法定代表人"
                    ),
                ),
                (
                    "registered_capital",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="注册资本"
                    ),
                ),
                (
                    "found_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="成立日期"
                    ),
                ),
                (
                    "business_term",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="营业期限"
                    ),
                ),
                (
                    "business_scope",
                    models.TextField(blank=True, null=True, verbose_name="经营范围"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_result",
                        to="ocr.recognitionrecord",
                        verbose_name="识别记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "营业执照识别结果",
                "verbose_name_plural": "营业执照识别结果",
                "db_table": "ocr_business_license_result",
            },
        ),
        migrations.CreateModel(
            name="VehicleLicenseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="号牌号码"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="车辆类型"
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所有人"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "engine_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="发动机号码"
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="VIN码"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="品牌型号"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="车辆品牌"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="车辆型号"
                    ),
                ),
                (
                    "vehicle_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="车辆名称"
                    ),
                ),
                (
                    "production_year",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="生产年份"
                    ),
                ),
                (
                    "register_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="注册日期"
                    ),
                ),
                (
                    "issue_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="发证日期"
                    ),
                ),
                (
                    "use_character",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="使用性质"
                    ),
                ),
                (
                    "file_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="档案编码"
                    ),
                ),
                (
                    "approved_passengers",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="核定载人数"
                    ),
                ),
                (
                    "gross_mass",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="总质量"
                    ),
                ),
                (
                    "unladen_mass",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="整备质量"
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="外廓尺寸"
                    ),
                ),
                (
                    "energy_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="燃料种类"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "inspection_record",
                    models.TextField(blank=True, null=True, verbose_name="校验记录"),
                ),
                (
                    "code_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="条码号"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_result",
                        to="ocr.recognitionrecord",
                        verbose_name="识别记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "行驶证识别结果",
                "verbose_name_plural": "行驶证识别结果",
                "db_table": "ocr_vehicle_license_result",
            },
        ),
        migrations.CreateModel(
            name="ScrapCarInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("matched", "已匹配"),
                            ("unmatched", "未匹配"),
                            ("manual_review", "待人工审核"),
                        ],
                        default="unmatched",
                        max_length=20,
                        verbose_name="匹配状态",
                    ),
                ),
                (
                    "match_score",
                    models.IntegerField(default=0, verbose_name="匹配分数"),
                ),
                (
                    "match_rules",
                    models.JSONField(default=dict, verbose_name="匹配规则"),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="报废单位或个人姓名",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="身份证号或信用代码",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="地址"
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="VIN码"
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="车牌号码"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="车辆类型"
                    ),
                ),
                (
                    "use_character",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="使用性质"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="车辆品牌"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="车辆型号"
                    ),
                ),
                (
                    "engine_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="发动机号码",
                    ),
                ),
                (
                    "approved_passengers",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="核定载人数"
                    ),
                ),
                (
                    "register_date",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="注册日期"
                    ),
                ),
                (
                    "energy_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="燃料种类"
                    ),
                ),
                (
                    "unladen_mass",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="整备质量"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="备注"
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="匹配时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "business_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_car_business_records",
                        to="ocr.recognitionrecord",
                        verbose_name="营业执照记录",
                    ),
                ),
                (
                    "id_card_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_car_id_card_records",
                        to="ocr.recognitionrecord",
                        verbose_name="身份证记录",
                    ),
                ),
                (
                    "vehicle_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrap_car_vehicle_records",
                        to="ocr.recognitionrecord",
                        verbose_name="行驶证记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "报废车信息识别",
                "verbose_name_plural": "报废车信息识别",
                "db_table": "ocr_scrap_car_info",
                "indexes": [
                    models.Index(
                        fields=["vehicle_number"], name="idx_scrap_vehicle_number"
                    ),
                    models.Index(fields=["owner_name"], name="idx_scrap_owner_name"),
                    models.Index(
                        fields=["match_status"], name="idx_scrap_match_status"
                    ),
                    models.Index(fields=["vin"], name="idx_scrap_vin"),
                    models.Index(fields=["created_at"], name="idx_scrap_created_at"),
                ],
            },
        ),
    ]
