# Generated by Django 5.2.6 on 2025-12-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
        ("vin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrinterface",
            name="vin_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vin_interfaces",
                to="vin.vinconfig",
                verbose_name="VIN查询配置",
            ),
        ),
    ]
