# Generated by Django 4.2.27 on 2026-01-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0002_ocrinterface_vin_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="idcardresult",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="手机号"
            ),
        ),
    ]
