# Generated by Django 4.2.27 on 2026-01-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0003_idcardresult_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapcarinfo",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="手机号"
            ),
        ),
    ]
