# Generated by Django 4.2.27 on 2026-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0004_scrapcarinfo_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognitionrecord",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="元数据"
            ),
        ),
    ]
