# Generated by Django 4.2.27 on 2026-01-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0005_recognitionrecord_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recognitionrecord",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="scrapcarinfo",
            name="phone_number",
        ),
    ]
