# Generated by Django 4.2.27 on 2026-01-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0006_remove_recognitionrecord_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapcarinfo",
            name="id_card_phone_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="手机号"
            ),
        ),
    ]
