# Generated by Django 4.2.27 on 2026-01-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0007_scrapcarinfo_id_card_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scrapcarinfo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "报废车信息识别",
                "verbose_name_plural": "报废车信息识别",
            },
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="ocr_scrap_c_vin_20801f_idx",
            old_name="idx_scrap_vin",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="ocr_scrap_c_vehicle_35a687_idx",
            old_name="idx_scrap_vehicle_number",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="ocr_scrap_c_owner_n_c5c2d8_idx",
            old_name="idx_scrap_owner_name",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="ocr_scrap_c_match_s_b81356_idx",
            old_name="idx_scrap_match_status",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="ocr_scrap_c_created_94a060_idx",
            old_name="idx_scrap_created_at",
        ),
    ]
