# Generated by Django 4.2.27 on 2026-01-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0008_alter_scrapcarinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scrapcarinfo",
            options={
                "verbose_name": "报废车信息识别",
                "verbose_name_plural": "报废车信息识别",
            },
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="idx_scrap_vehicle_number",
            old_name="ocr_scrap_c_vehicle_35a687_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="idx_scrap_owner_name",
            old_name="ocr_scrap_c_owner_n_c5c2d8_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="idx_scrap_match_status",
            old_name="ocr_scrap_c_match_s_b81356_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="idx_scrap_vin",
            old_name="ocr_scrap_c_vin_20801f_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapcarinfo",
            new_name="idx_scrap_created_at",
            old_name="ocr_scrap_c_created_94a060_idx",
        ),
        migrations.AddField(
            model_name="scrapcarinfo",
            name="business_license_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrap_car_business_results",
                to="ocr.businesslicenseresult",
                verbose_name="营业执照识别结果",
            ),
        ),
        migrations.AddField(
            model_name="scrapcarinfo",
            name="id_card_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrap_car_id_card_results",
                to="ocr.idcardresult",
                verbose_name="身份证识别结果",
            ),
        ),
        migrations.AddField(
            model_name="scrapcarinfo",
            name="vehicle_license_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrap_car_vehicle_results",
                to="ocr.vehiclelicenseresult",
                verbose_name="行驶证识别结果",
            ),
        ),
    ]
